spring:
  datasource:
    url: #
    username:
    password:
  jpa:
    database-platform:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    async:
      request-timeout: 3600000
server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: true

