spring:
  security:
    saml2:
      relyingparty: # Configuration for the SAML 2.0 Relying Party (your application)
        registration:
          okta: # Registration ID for this Relying Party configuration (you can choose any ID, 'okta' is used here)
            assertingparty: # Configuration for the Asserting Party (Identity Provider - in this case, Okta)
              metadata-uri: https://dev-32534403.okta.com/app/exknid22hbn8vmKU05d7/sso/saml/metadata # URL of Okta's SAML metadata endpoint. Spring Security fetches metadata from here.
            signing: # Configuration for signing and verifying SAML messages
              credentials: # Credentials used by your application for signing requests and verifying responses
                #                  src/main/resources/local.key # Path to your private key file (commented out example of file path)
                - private-key-location: classpath:local.key # Location of your private key file in the classpath (e.g., src/main/resources/local.key) - used to sign SAML requests.
                  #                  src/main/resources/local.crt # Path to your certificate file (commented out example of file path)
                  certificate-location: classpath:local.crt # Location of your certificate file in the classpath (e.g., src/main/resources/local.crt) -  your public certificate, used by Okta to verify signatures from your app.
            singlelogout: # Configuration for Single Logout (SLO)
              binding: POST # Binding for SLO requests and responses. POST binding is commonly used for SLO.
              response-url: "{baseUrl}/logout/saml2/slo" # URL in your application to handle SAML SLO responses. {baseUrl} is a placeholder for your application's base URL.

# POTENTIAL AUTH0 AND OKTA INTEGRATION; SCALABILITY?
#spring:
#  security:
#    saml2:
#      relyingparty:
#        registration:
#          auth0:
#            assertingparty:
#              metadata-uri: <your-auth0-metadata-uri>
#            signing:
#              credentials: &signing-credentials
#                - private-key-location: classpath:local.key
#                  certificate-location: classpath:local.crt
#            singlelogout: &logout-settings
#              binding: POST
#              response-url: "{baseUrl}/logout/saml2/slo"
#          okta:
#            assertingparty:
#              metadata-uri: <your-okta-metadata-uri>
#            signing:
#              credentials: *signing-credentials
#            singlelogout: *logout-settings
#
