#Start database using command `mysql.server start`
spring:
  #Datasource: an object that manages the connection to your database
  datasource:
    #Stopped at 35:05
    url: jdbc:mysql://localhost:3306/patient_database?serverTimezone=UTC #
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    async:
      request-timeout: 3600000
server:
  port: 3306
  error:
    path: /user/error
    whitelabel:
      enabled: true

